### ISSUE TITLE
REQUEST: Provide method to provide json list of codenames

### ISSUE THREAD

**Issue by myspivey** [nfantone/gulp-release#12]
gulp-codename supports providing a custom list, would be great to be able to expose this.

**Comment by nfantone** [comment]
Good idea. Will start working.

**Comment by nfantone** [comment]
@myspivey Implemented in https://github.com/nfantone/gulp-release/pull/14

Wanna try it out and give me some feedback before merging?

**Comment by myspivey** [comment]
@nfantone will check it out here shortly.

**Comment by myspivey** [comment]
Working great on PR #14! Tested both with providing list of names and without.

**Comment by nfantone** [comment]
@myspivey Excellent! Merging and releasing, then.
