### ISSUE TITLE
Problem escaping quotes in git push 

### ISSUE THREAD

**Issue by gravitycode** [nfantone/gulp-release#2]
I have a problem when i want to push changes to origin. The problem is when declare the branches to push:

Error: Command failed: /bin/sh -c git push origin 'develop master' --tags

Would there be an elegant way to solve it ?

Thanks

**Comment by nfantone** [comment]
Looks like a regression from 1.0.6. I'll have a look.

**Comment by nfantone** [comment]
@gravitycode Confirmed. Fixing it now.

**Comment by nfantone** [comment]
@gravitycode This was a tad harder than expected. It turns out, there is no way of defining multiple refspecs to be pushed using `gulp-git`.

Or should I say _there was_ no way. I've created a PR for that. You can track it here: https://github.com/stevelacy/gulp-git/pull/123

**Comment by gravitycode** [comment]
I have updated gulp-git to 1.8.0. I couldnt test it yet but it is very likely that everything works well. Thank you so much @nfantone

**Comment by nfantone** [comment]
@gravitycode [1.0.7](https://www.npmjs.com/package/gulp-release) has been released, which addresses this issue along with latest gulp-git version!
