### ISSUE TITLE
Errors with new gulp-bump and gulp-git version

### ISSUE THREAD

**Issue by gravitycode** [nfantone/gulp-release#20]
Hi,
I believe that the update of the transitive dependencies has broken the libray.

gulp-release 1.1.0 have dependencies from:
"gulp-bump": "^2.4.0",
"gulp-git": "^1.11.0",

At this moment, this download:
"gulp-bump" -> 2.5.0"  (published 1 Nov)
"gulp-git" -> 1.12.0" (published 19 Oct)

I do not know since when it happens but now it does not work. 
I think it's because of the transitive dependencies

gulp-bump transform de package version '2016.0.1' to '22016.0.1' or '16.0.1' to '116.0.2'. 
The new version number is wrong and this breaks the branch fetch.

gulp-release give me the following error 
Error: Command `git flow release finish -m 'CODE' 116.0.2` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by nfantone** [comment]
Hi, @gravitycode!

I just tested this out and it's working fine for me. Could you try the old `rm -rf node_modules && npm i` for me, please, if you haven't already done so?

**Comment by gravitycode** [comment]
I tried with a fresh node_modules/ and with this versions in my package.json:
"version": "1.0.0-SNAPSHOT"  Works!

"version": "2016.0.1-SNAPSHOT" It Doesn`t work

Log:
[14:26:09] Starting 'release'...
[14:26:09] Starting 'release:start'...
[14:26:09] git flow release start -F 2016.0.1
Switched to a new branch 'release/2016.0.1'

Summary of actions:
- A new branch 'release/2016.0.1' was created, based on 'develop'
- You are now on branch 'release/2016.0.1'

Follow-up actions:
- Bump the version number now!
- Start committing last-minute fixes in preparing your release
- When done, run:

     git flow release finish '2016.0.1'

[14:26:10] Finished 'release:start' after 575 ms
[14:26:10] Starting 'bump'...
[14:26:10] Bumped 016.0.1-SNAPSHOT to 2016.0.1 with type: patch
[14:26:10] Finished 'bump' after 39 ms
[14:26:10] Starting 'release:commit'...
[14:26:10] Finished 'release:commit' after 33 ms
[14:26:10] Starting 'release:finish'...
[14:26:10] git flow release finish -m 'CODE' **22016.0.1**
Fatal: Branch 'release/**22016.0.1**' does not exist and is required.
[14:26:10] 'release:finish' errored after 539 ms
[14:26:10] Error: Command `git flow release finish -m 'CODE' **22016.0.1**` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)


This version number is accepted by semver

**Comment by nfantone** [comment]
@gravitycode Ok, got it. So your issue is with a particular kind of version tag format.

Could you please show me how are you running the release command?

**Comment by gravitycode** [comment]
i am running with:
`gulp release -m CODE --push`

release.register(gulp, {
    tasks: {
        release: 'release'
    },
    messages: {
        bump: '[gitflow-task] Updating package.json -> Bumping release version',
        next: '[gitflow-task] Updating package.json -> Setting next development version'
    },
    packages: ['./package.json'],
    devSuffix:"-SNAPSHOT"
});

**Comment by nfantone** [comment]
@gravitycode Thanks. Lastly, could you show me what version is currently on your `package.json` of the `develop` branch? I'm guessing it's `016.0.1-SNAPSHOT`?

**Comment by gravitycode** [comment]
"2016.0.1-SNAPSHOT" After it launched:
- In develop branch -> "2016.0.1-SNAPSHOT"
- In release/2016.0.1 branch -> "22016.0.1"

**Comment by nfantone** [comment]
I mean, the version before executing the command (the one that gets bumped).

Nevertheless, this right here:

```sh
[14:26:10] Bumped 016.0.1-SNAPSHOT to 2016.0.1 with type: patch
```

seems wrong to me and should be reported to `gulp-bump`. It's only a suspicion for the moment.

**Comment by gravitycode** [comment]
And what is the motivation to keep the dependencies open (^)? this is very weak :(

**Comment by nfantone** [comment]
@gravitycode I'm sorry this is causing you trouble, right now.

Dependencies aren't "open". They are actually using a _caret_ (`^`) symbol, which means that only _backwards compatible changes_ should be included in any future release. I know we don't live in an ideal world. But what happened to you today, shouldn't have. And now, thanks to you, we spotted a bug.

I wouldn't call that "_weak_", like you put it.

**Comment by gravitycode** [comment]
@nfantone Thank you for you unbeatable support

**Comment by nfantone** [comment]
I see you already opened an issue over at `gulp-bump`. Thanks for that.

And while we are on the topic, think of this the other way around. Let's say now they fix the bug on `gulp-bump` and they cut a new public release. Had I anchored its version number on this project's `package.json`, then _I_ would have to manually update the version and proceed to release yet a newer version of `gulp-release`, just to include the fix. By using the `^`, none of that happens and people just what they need without further intervention.

Moreover, most open source projects out there go along with this practice. Even [big ones](https://github.com/gulpjs/gulp/blob/master/package.json#L28).

**Comment by gravitycode** [comment]
I understand. Thank for your explanation. This practice speeds up bug find and resolution. Thank you again!

**Comment by nfantone** [comment]
Closing this as was fixed [at `gulp-bump`](https://github.com/stevelacy/gulp-bump/issues/62#issuecomment-262601196).
