### ISSUE TITLE
Node 8 Support

### ISSUE THREAD

**Issue by damienwebdev** [nfantone/gulp-release#35]
The dependency `gulp-git` got a [version bump](https://github.com/stevelacy/gulp-git/releases/tag/gulp-git%402.3.2) to `2.3.2` for compatability with Node 8, currently `gulp release` fails on a fresh install on Node 8.

The [relevant issue](https://github.com/stevelacy/gulp-git/issues/164) in `gulp-git`

**Comment by nfantone** [comment]
@damienwebdev Thanks for letting me know :). I've been a little lazy on updates, so apologies for that. I'm working on updating deps on the project right now.

**Comment by nfantone** [comment]
@damienwebdev `1.2.0` has been [released](https://www.npmjs.com/package/gulp-release). Care to try it out?

**Comment by damienwebdev** [comment]
lgtm. Thanks!
